### ISSUE TITLE
Notizen zum Seminar

### ISSUE THREAD

**Issue by christian-leingang** [vjarai/jarai.cpp.complete#1]
Hallo Herr Jarai,

vielen Dank nochmals für das tolle Seminar über C++!

Da ich es am Freitag vergessen habe, Ihnen meine Notizen bereitzustellen, können Sie diese über den Link abrufen: 
https://gist.github.com/christian-leingang/4b6463270e479b2519d13d5bec319925

**Comment by vjarai** [comment]
Hallo Herr Leingang,

Vielen Dank, ihre Notizen sind wirklich gut und bringen es auf den Punkt!

Ich könnte mir vorstellen, dass dieses Buch für Sie recht interessant ist… :-)

https://smile.amazon.de/dp/1484259483/?coliid=I1SQEU94FMUS9Z&colid=30Z4B5V55CQYY&psc=1&ref_=lv_ov_lig_dp_it


Grüße Viktor Jarai

(Von unterwegs gesendet)

Am 23.01.2023 um 14:12 schrieb Christian Leingang ***@***.***>:

﻿

Hallo Herr Jarai,

vielen Dank nochmals für das tolle Seminar über C++!

Da ich es am Freitag vergessen habe, Ihnen meine Notizen bereitzustellen, können Sie diese über den Link abrufen:
https://gist.github.com/christian-leingang/4b6463270e479b2519d13d5bec319925
